/*
 * App URI: app/mypage/mypage
 * Source Location: app/mypage/mypage.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5545), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("app/mypage/mypage", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * contents_container.js
			 * Created at 2025. 4. 17. 오후 1:52:50.
			 *
			 * @author gyrud
			 ************************************************/
			//로그아웃 처리하는 메서드가 인자로 액세스 토큰 값을 받는데 js에선 그걸 못하니까 유저 아이디 값을 로컬 스토리지에 저장.


			function getCookieValue(name) {
			   const cookie = document.cookie
			        .split('; ')
			        .find(row => row.indexOf(name + '=') === 0);
			    
			    return cookie ? cookie.split('=')[1] : null;
			}

			/*
			 * "로그아웃" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e) {
				
				var btn = e.control;
				
				const userId = localStorage.getItem("userId") || getCookieValue("userId");
				
				if (!userId) {
			        alert("로그인 정보가 없습니다. (401 Unauthorized)");
			        return;
			    }
				
			    var dm = app.lookup("dmLogout");
			    dm.setValue("userId", userId);
			    app.lookup("smsLogout").send(); // 서버 전송
			    
			}

			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출.
			 * 통신이 성공하면 발생합니다.
			 */
			function onSmsLogoutSubmitSuccess(e){
				var smsLogout = e.control;
				localStorage.removeItem("userId");
			    console.log("✅ userId 삭제됨");

			    // 원하는 경로로 이동
			    location.href = "/users/login";
			};
			// End - User Script
			
			// Header
			var dataMap_1 = new cpr.data.DataMap("dmLogout");
			dataMap_1.parseData({
				"columns" : [{
					"name": "userId",
					"dataType": "number"
				}]
			});
			app.register(dataMap_1);
			var submission_1 = new cpr.protocols.Submission("smsLogout");
			submission_1.action = "http://localhost:7079/api/users/logout";
			submission_1.mediaType = "application/json";
			submission_1.addRequestData(dataMap_1);
			if(typeof onSmsLogoutSubmitSuccess == "function") {
				submission_1.addEventListener("submit-success", onSmsLogoutSubmitSuccess);
			}
			app.register(submission_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["contents-container"]);
			container.style.css({
				"background-color" : "#FFFFFF",
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var responsiveXYLayout_1 = new cpr.controls.layouts.ResponsiveXYLayout();
			container.setLayout(responsiveXYLayout_1);
			
			// UI Configuration
			var userDefinedControl_1 = new udc.mypage.profile("profile");
			container.addChild(userDefinedControl_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "50px",
						"width": "520px",
						"height": "124px",
						"left": "calc(50% - 260px)"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "50px",
						"width": "254px",
						"height": "124px",
						"left": "calc(50% - 127px)"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "50px",
						"width": "178px",
						"height": "124px",
						"left": "calc(50% - 89px)"
					}
				]
			});
		}
	});
	app.title = "mypage";
	cpr.core.Platform.INSTANCE.register(app);
})();
