/*
 * App URI: app/mypage/mypage
 * Source Location: app/mypage/mypage.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5545), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("app/mypage/mypage", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * contents_container.js
			 * Created at 2025. 4. 17. 오후 1:52:50.
			 *
			 * @author gyrud
			 ************************************************/

			/*
			 * "로그아웃" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e) {
				
				var btn = e.control;
			    app.lookup("smsLogout").send(); // 서버 전송
			    
			}

			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출.
			 * 통신이 성공하면 발생합니다.
			 */
			function onSmsLogoutSubmitSuccess(e){
				var smsLogout = e.control;
			    // 원하는 경로로 이동
			    location.href = "/auth/login";
			}

			/*
			 * 서브미션에서 receive 이벤트 발생 시 호출.
			 * 서버로 부터 데이터를 모두 전송받았을 때 발생합니다.
			 */
			function onSmsLogoutReceive(e){
				var smsLogout = e.control;
				
				var xhr = smsLogout.xhr;
				var res = JSON.parse(xhr.responseText);
				console.log(res);
				if (res === true) {
					alert("로그아웃 되었습니다!");
				} else {
					alert("로그아웃에 실패하였습니다!");
					e.preventDefault();
				}
				
			}

			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad(e){
				var name = app.lookup("name");
				var smsName = app.lookup("smsName");
				
				 smsName.addEventListener("submit-success", function(e) {
			        var nicknameValue = name.getValue("nickname");

			        var nickname = app.lookup("nickname");

			        nickname.value = nicknameValue;
			        console.log("✅ 닉네임:", nicknameValue);
			    });
				
				smsName.send();
				
				
			}

			/*
			 * "구독 및 결제 관리" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick2(e){
				var button = e.control;
				window.location.href = window.location.origin + "/users/payment"
			};
			// End - User Script
			
			// Header
			var dataMap_1 = new cpr.data.DataMap("dmLogout");
			dataMap_1.parseData({
				"columns" : [{
					"name": "userId",
					"dataType": "number"
				}]
			});
			app.register(dataMap_1);
			
			var dataMap_2 = new cpr.data.DataMap("dmHealthInfo");
			dataMap_2.parseData({});
			app.register(dataMap_2);
			
			var dataMap_3 = new cpr.data.DataMap("name");
			dataMap_3.parseData({
				"columns" : [{"name": "nickname"}]
			});
			app.register(dataMap_3);
			var submission_1 = new cpr.protocols.Submission("smsLogout");
			submission_1.withCredentials = true;
			submission_1.action = "/api/users/logout";
			submission_1.mediaType = "application/json";
			submission_1.addRequestData(dataMap_1);
			if(typeof onSmsLogoutSubmitSuccess == "function") {
				submission_1.addEventListener("submit-success", onSmsLogoutSubmitSuccess);
			}
			app.register(submission_1);
			
			var submission_2 = new cpr.protocols.Submission("smsName");
			submission_2.action = "/api/mypage/nickname";
			submission_2.addResponseData(dataMap_3, false);
			app.register(submission_2);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["contents-container"]);
			container.style.css({
				"background-color" : "#FFFFFF",
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var responsiveXYLayout_1 = new cpr.controls.layouts.ResponsiveXYLayout();
			container.setLayout(responsiveXYLayout_1);
			
			// UI Configuration
			var userDefinedControl_1 = new udc.mypage.profile("profile");
			container.addChild(userDefinedControl_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "50px",
						"width": "520px",
						"height": "124px",
						"left": "calc(50% - 260px)"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "50px",
						"width": "254px",
						"height": "124px",
						"left": "calc(50% - 127px)"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "50px",
						"width": "178px",
						"height": "124px",
						"left": "calc(50% - 89px)"
					}
				]
			});
			
			var userDefinedControl_2 = new udc.mypage.infoHealth();
			container.addChild(userDefinedControl_2, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "633px",
						"width": "520px",
						"height": "440px",
						"left": "calc(50% - 260px)"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "633px",
						"width": "254px",
						"height": "440px",
						"left": "calc(50% - 127px)"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "633px",
						"width": "178px",
						"height": "440px",
						"left": "calc(50% - 89px)"
					}
				]
			});
			
			var userDefinedControl_3 = new udc.mypage.infoExpired();
			container.addChild(userDefinedControl_3, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "183px",
						"width": "520px",
						"height": "440px",
						"left": "calc(50% - 260px)"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "183px",
						"width": "254px",
						"height": "440px",
						"left": "calc(50% - 127px)"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "183px",
						"width": "178px",
						"height": "440px",
						"left": "calc(50% - 89px)"
					}
				]
			});
			
			var button_1 = new cpr.controls.Button();
			button_1.value = "Button";
			container.addChild(button_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "1106px",
						"width": "0px",
						"height": "66px",
						"left": "calc(50% - 0px)"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "1106px",
						"width": "0px",
						"height": "66px",
						"left": "calc(50% - 0px)"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "1106px",
						"width": "0px",
						"height": "66px",
						"left": "calc(50% - 0px)"
					}
				]
			});
			
			var button_2 = new cpr.controls.Button();
			button_2.value = "구독 및 결제 관리";
			if(typeof onButtonClick2 == "function") {
				button_2.addEventListener("click", onButtonClick2);
			}
			container.addChild(button_2, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "1093px",
						"width": "520px",
						"height": "66px",
						"left": "calc(50% - 260px)"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "1093px",
						"width": "254px",
						"height": "66px",
						"left": "calc(50% - 127px)"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "1093px",
						"width": "178px",
						"height": "66px",
						"left": "calc(50% - 89px)"
					}
				]
			});
			
			var group_1 = new cpr.controls.Container();
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_1);
			(function(container){
				var group_2 = new cpr.controls.Container();
				var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
				flowLayout_1.scrollable = false;
				group_2.setLayout(flowLayout_1);
				(function(container){
					var output_1 = new cpr.controls.Output("nickname");
					output_1.value = "Output";
					output_1.style.css({
						"text-align" : "center"
					});
					container.addChild(output_1, {
						"width": "auto",
						"height": "20px"
					});
					var output_2 = new cpr.controls.Output();
					output_2.value = "님 환영합니다!";
					container.addChild(output_2, {
						"width": "302px",
						"height": "20px"
					});
				})(group_2);
				container.addChild(group_2, {
					"top": "0px",
					"left": "0px",
					"width": "412px",
					"height": "20px"
				});
				var button_3 = new cpr.controls.Button();
				button_3.value = "로그아웃";
				button_3.style.css({
					"border-radius" : "5px"
				});
				if(typeof onButtonClick == "function") {
					button_3.addEventListener("click", onButtonClick);
				}
				container.addChild(button_3, {
					"left": "417px",
					"width": "100px",
					"height": "20px",
					"top": "calc(50% - 10px)"
				});
			})(group_1);
			container.addChild(group_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "20px",
						"width": "520px",
						"height": "20px",
						"left": "calc(50% - 260px)"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "20px",
						"width": "254px",
						"height": "20px",
						"left": "calc(50% - 127px)"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "20px",
						"width": "178px",
						"height": "20px",
						"left": "calc(50% - 89px)"
					}
				]
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "mypage";
	cpr.core.Platform.INSTANCE.register(app);
})();
