/*
 * App URI: app/mypage/passwordchange
 * Source Location: app/mypage/passwordchange.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5545), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("app/mypage/passwordchange", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * contents_container.js
			 * Created at 2025. 4. 17. 오후 1:52:50.
			 *
			 * @author gyrud
			 ************************************************/;
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["contents-container"]);
			container.style.css({
				"background-color" : "#FFFFFF",
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var responsiveXYLayout_1 = new cpr.controls.layouts.ResponsiveXYLayout();
			container.setLayout(responsiveXYLayout_1);
			
			// UI Configuration
			var output_1 = new cpr.controls.Output();
			output_1.value = "내 정보 변경 페이지";
			output_1.style.css({
				"color" : "#000000",
				"font-weight" : "bold",
				"font-size" : "24px",
				"font-family" : "Kim jung chul Myungjo Regular"
			});
			container.addChild(output_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "49px",
						"left": "40px",
						"width": "520px",
						"height": "74px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "49px",
						"left": "20px",
						"width": "254px",
						"height": "74px"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "49px",
						"left": "14px",
						"width": "178px",
						"height": "74px"
					}
				]
			});
			
			var inputBox_1 = new cpr.controls.InputBox("ipb1");
			inputBox_1.placeholder = "현재 비밀번호 입력";
			inputBox_1.style.css({
				"border-radius" : "5px",
				"text-align" : "center"
			});
			container.addChild(inputBox_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "158px",
						"left": "40px",
						"width": "520px",
						"height": "52px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "158px",
						"left": "20px",
						"width": "254px",
						"height": "52px"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "158px",
						"left": "14px",
						"width": "178px",
						"height": "52px"
					}
				]
			});
			
			var inputBox_2 = new cpr.controls.InputBox("ipb2");
			inputBox_2.placeholder = "새 비밀번호 입력";
			inputBox_2.style.css({
				"border-radius" : "5px",
				"text-align" : "center"
			});
			container.addChild(inputBox_2, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "220px",
						"left": "40px",
						"width": "520px",
						"height": "52px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "220px",
						"left": "20px",
						"width": "254px",
						"height": "52px"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "220px",
						"left": "14px",
						"width": "178px",
						"height": "52px"
					}
				]
			});
			
			var button_1 = new cpr.controls.Button();
			button_1.value = "변경하기";
			button_1.style.css({
				"border-radius" : "5px"
			});
			container.addChild(button_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "344px",
						"left": "40px",
						"width": "520px",
						"height": "52px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "344px",
						"left": "20px",
						"width": "254px",
						"height": "52px"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "344px",
						"left": "14px",
						"width": "178px",
						"height": "52px"
					}
				]
			});
			
			var inputBox_3 = new cpr.controls.InputBox("ipb3");
			inputBox_3.placeholder = "새 비밀번호 확인";
			inputBox_3.style.css({
				"border-radius" : "5px",
				"text-align" : "center"
			});
			container.addChild(inputBox_3, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "282px",
						"left": "40px",
						"width": "520px",
						"height": "52px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "282px",
						"left": "20px",
						"width": "254px",
						"height": "52px"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "282px",
						"left": "14px",
						"width": "178px",
						"height": "52px"
					}
				]
			});
		}
	});
	app.title = "passwordchange";
	cpr.core.Platform.INSTANCE.register(app);
})();
