/*
 * App URI: app/home/home
 * Source Location: app/home/home.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5545), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("app/home/home", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * contents_container.js
			 * Created at 2025. 4. 17. 오후 1:52:50.
			 *
			 * @author gyrud
			 ************************************************/

			const createRecipeCardModule = cpr.core.Module.require("module/recipe/createRecipeCard");
			const createRecipeCard = createRecipeCardModule.createRecipeCard;

			const slidify = cpr.core.Module.require("module/common/Slidifiy").slidify;

			/*
			 * 루트 컨테이너에서 init 이벤트 발생 시 호출.
			 * 앱이 최초 구성될 때 발생하는 이벤트 입니다.
			 */
			function onBodyInit(e){
				const slide = slidify(app.lookup("bannerGroup"));
				slide.showCount = 1;
				slide.autoPlay(true);
				slide.start();
			}

			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad(e){
				const popularRecipeListSms = app.lookup("popularRecipeListSms");
				popularRecipeListSms.send();
				app.lookup("popularSearchSms").send();
			}

			/*
			 * "레시피 더보기" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
				var button = e.control;
				window.location.href = "/recipe";
			}

			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출.
			 * 통신이 성공하면 발생합니다.
			 */
			function onPopularRecipeListSmsSubmitSuccess(e){
				const popularRecipeListSms = e.control;
				
				const recipeContainer = app.lookup("popluarRecipeList"); 

				const result = popularRecipeListSms.xhr.responseText;
				const resultJson = JSON.parse(result);
				
				createRecipeCard(resultJson, recipeContainer);
				
				const slide = slidify(recipeContainer);
				
				slide.autoPlay(true);
				slide.start();

				recipeContainer.redraw();
			}

			// 데이터셋의 모든 행을 순회하며 아웃풋 컨트롤에 값 할당하기
			function setDataToOutputs() {
			    // 데이터셋 객체 참조
			    var ds = app.lookup("popularSearch");  // 사용하려는 데이터셋 ID로 변경
			    
			    // 데이터셋의 행 수 확인
			    var rowCount = ds.getRowCount();
			    console.log("Row Count: " + rowCount);
			    
			    // 출력할 컨트롤들이 있는 배열 또는 컨트롤 ID 패턴 정의
			    var outputPrefix = "out";
			    
			    // 데이터셋의 각 행을 순회하며 해당 컨트롤에 값 할당
			    for(var i = 0; i < rowCount; i++) {
			        // 키워드와 recipeId 값 가져오기 (id 대신 recipeId 사용)
			        var keyword = ds.getValue(i, "keyword");
			        var recipeId = ds.getValue(i, "recipeId");  // 컬럼명 수정
			        
			        // 해당 값을 i번째 아웃풋 컨트롤에 설정
			        var outputId = outputPrefix + (i + 1);
			        let outputControl = app.lookup(outputId);
			        
			        if (outputControl) {
			            // 값 설정 (순위 표시 추가)
			            outputControl.value = (i + 1) + ". " + keyword;
			            
			            // 사용자 데이터에 recipeId 저장
			            outputControl.userData("recipeId", recipeId);
			            
			            // 클릭 이벤트 핸들러 추가
			            outputControl.removeEventListeners("click");
			            outputControl.addEventListener("click", function(e) {
			                var control = e.control;
			                var recipeId = control.userData("recipeId");
			                
			                if (recipeId) {

			                   window.location.href = "/recipe/" + recipeId;
			                    console.log("이동: /recipe/" + recipeId);
			                }
			            });
			            
			            // 클릭 가능함을 시각적으로 표시
			            outputControl.style.css({
			                "cursor": "pointer",
			                "text-decoration": "underline"
			            });
			        }
			    }
			}




			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출.
			 * 통신이 성공하면 발생합니다.
			 */
			function onPopularSearchSmsSubmitSuccess(e){
				var popularSearchSms = e.control;
				setDataToOutputs();
				app.lookup("popularSearchBoard").redraw();
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("popularSearch");
			dataSet_1.parseData({
				"columns" : [
					{"name": "keyword"},
					{"name": "count"},
					{"name": "recipeId"}
				]
			});
			app.register(dataSet_1);
			var submission_1 = new cpr.protocols.Submission("popularRecipeListSms");
			submission_1.action = "/api/recipes/popular";
			if(typeof onPopularRecipeListSmsSubmitSuccess == "function") {
				submission_1.addEventListener("submit-success", onPopularRecipeListSmsSubmitSuccess);
			}
			app.register(submission_1);
			
			var submission_2 = new cpr.protocols.Submission("popularSearchSms");
			submission_2.method = "get";
			submission_2.action = "/api/recipe/search/popular";
			submission_2.addResponseData(dataSet_1, false);
			if(typeof onPopularSearchSmsSubmitSuccess == "function") {
				submission_2.addEventListener("submit-success", onPopularSearchSmsSubmitSuccess);
			}
			app.register(submission_2);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["contents-container"]);
			container.style.css({
				"background-color" : "#FFFFFF",
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var responsiveXYLayout_1 = new cpr.controls.layouts.ResponsiveXYLayout();
			container.setLayout(responsiveXYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("bannerGroup");
			var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
			group_1.setLayout(flowLayout_1);
			(function(container){
				var image_1 = new cpr.controls.Image();
				image_1.src = "theme/images/banner_service_intro.svg";
				image_1.style.item.css({
					"fill" : "true"
				});
				container.addChild(image_1, {
					"autoSize": "none",
					"width": "100%",
					"height": "100%"
				});
				var image_2 = new cpr.controls.Image();
				image_2.src = "theme/images/banner_service_intro.svg";
				image_2.style.item.css({
					"fill" : "true"
				});
				container.addChild(image_2, {
					"autoSize": "none",
					"width": "100%",
					"height": "100%"
				});
			})(group_1);
			container.addChild(group_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "0px",
						"right": "0px",
						"left": "0px",
						"height": "300px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "0px",
						"right": "0px",
						"left": "0px",
						"height": "300px"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "0px",
						"right": "0px",
						"left": "0px",
						"height": "300px"
					}
				]
			});
			
			var group_2 = new cpr.controls.Container("popularSearchBoard");
			group_2.style.css({
				"background-color" : "#FBDBCF",
				"border-radius" : "5px"
			});
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 20;
			verticalLayout_1.leftMargin = 20;
			verticalLayout_1.rightMargin = 20;
			verticalLayout_1.topMargin = 20;
			verticalLayout_1.bottomMargin = 20;
			group_2.setLayout(verticalLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "실시간 레시피 인기 검색어";
				output_1.style.css({
					"color" : "#856C66",
					"font-weight" : "bold",
					"font-size" : "20px",
					"text-align" : "center"
				});
				container.addChild(output_1, {
					"width": "100px",
					"height": "30px"
				});
				var output_2 = new cpr.controls.Output("out1");
				output_2.value = "Output";
				output_2.style.css({
					"font-weight" : "bold",
					"font-size" : "16px"
				});
				container.addChild(output_2, {
					"width": "487px",
					"height": "25px"
				});
				var output_3 = new cpr.controls.Output("out2");
				output_3.value = "Output";
				output_3.style.css({
					"font-weight" : "bold",
					"font-size" : "16px"
				});
				container.addChild(output_3, {
					"autoSize": "none",
					"width": "560px",
					"height": "25px"
				});
				var output_4 = new cpr.controls.Output("out3");
				output_4.value = "Output";
				output_4.style.css({
					"font-weight" : "bold",
					"font-size" : "16px"
				});
				container.addChild(output_4, {
					"autoSize": "none",
					"width": "560px",
					"height": "25px"
				});
				var output_5 = new cpr.controls.Output("out4");
				output_5.value = "Output";
				output_5.style.css({
					"font-weight" : "bold",
					"font-size" : "16px"
				});
				container.addChild(output_5, {
					"autoSize": "none",
					"width": "560px",
					"height": "25px"
				});
				var output_6 = new cpr.controls.Output("out5");
				output_6.value = "Output";
				output_6.style.css({
					"font-weight" : "bold",
					"font-size" : "16px"
				});
				container.addChild(output_6, {
					"autoSize": "none",
					"width": "560px",
					"height": "25px"
				});
			})(group_2);
			container.addChild(group_2, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "340px",
						"right": "0px",
						"left": "0px",
						"height": "300px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "340px",
						"right": "0px",
						"left": "0px",
						"height": "300px"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "340px",
						"right": "0px",
						"left": "0px",
						"height": "300px"
					}
				]
			});
			
			var group_3 = new cpr.controls.Container();
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.scrollable = false;
			verticalLayout_2.spacing = 20;
			group_3.setLayout(verticalLayout_2);
			(function(container){
				var group_4 = new cpr.controls.Container();
				var xYLayout_1 = new cpr.controls.layouts.XYLayout();
				xYLayout_1.scrollable = false;
				group_4.setLayout(xYLayout_1);
				(function(container){
					var userDefinedControl_1 = new udc.recipe.recipe_title();
					userDefinedControl_1.value = "인기 레시피";
					container.addChild(userDefinedControl_1, {
						"top": "0px",
						"bottom": "0px",
						"left": "0px",
						"width": "200px"
					});
					var button_1 = new cpr.controls.Button();
					button_1.value = "레시피 더보기";
					if(typeof onButtonClick == "function") {
						button_1.addEventListener("click", onButtonClick);
					}
					container.addChild(button_1, {
						"top": "0px",
						"right": "0px",
						"bottom": "0px",
						"width": "100px"
					});
				})(group_4);
				container.addChild(group_4, {
					"autoSize": "height",
					"width": "400px",
					"height": "30px"
				});
				var group_5 = new cpr.controls.Container("popluarRecipeList");
				var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
				flowLayout_2.scrollable = false;
				flowLayout_2.horizontalSpacing = 20;
				flowLayout_2.verticalSpacing = 20;
				flowLayout_2.horizontalAlign = "center";
				flowLayout_2.verticalAlign = "top";
				flowLayout_2.lineWrap = true;
				flowLayout_2.maxContentWidth = -1;
				group_5.setLayout(flowLayout_2);
				container.addChild(group_5, {
					"autoSize": "none",
					"width": "600px",
					"height": "420px"
				});
			})(group_3);
			container.addChild(group_3, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "670px",
						"right": "0px",
						"left": "0px",
						"height": "500px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "670px",
						"right": "0px",
						"left": "0px",
						"height": "500px"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "670px",
						"right": "0px",
						"left": "0px",
						"height": "500px"
					}
				]
			});
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "home";
	cpr.core.Platform.INSTANCE.register(app);
})();
