/*
 * App URI: app/layout/layout
 * Source Location: app/layout/layout.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5481), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("app/layout/layout", { 
		onPrepare: function(loader) {
			loader.addCSS("theme/custom/layout.part.css");
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * layout.js
			 * Created at 2025. 4. 10. 오후 6:42:47.
			 *
			 * @author gyrud
			 ************************************************/

			let pathName = "";

			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad(e){
				const subList = app.lookup("sms1");
				subList.send();
				
				pathName = window.location.pathname;
			}

			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출.
			 * 통신이 성공하면 발생합니다.
			 */
			function onSms1SubmitSuccess(e){

				var embeddedRoutes = app.lookup("embeddedRoutes");
				var voRow = embeddedRoutes.findFirstRow("path == '" + pathName + "'");
				
				if (voRow != null) {
					const vsAppId = voRow.getValue("app");
					const vcEmb = app.lookup("ea1");
					
					cpr.core.App.load(vsAppId, function(loadedApp){ 
						if(loadedApp){
							vcEmb.app = loadedApp; 
						} 
					});
					
					app.getContainer().redraw();	
				}
				
			   
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("embeddedRoutes");
			dataSet_1.parseData({
				"columns" : [
					{"name": "path"},
					{"name": "app"}
				]
			});
			app.register(dataSet_1);
			var submission_1 = new cpr.protocols.Submission("sms1");
			submission_1.action = "/api/page-routes";
			submission_1.mediaType = "application/json";
			submission_1.addResponseData(dataSet_1, false);
			if(typeof onSms1Receive2 == "function") {
				submission_1.addEventListener("receive", onSms1Receive2);
			}
			if(typeof onSms1SubmitSuccess == "function") {
				submission_1.addEventListener("submit-success", onSms1SubmitSuccess);
			}
			app.register(submission_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"background-color" : "#F3F1F0",
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("layout-container");
			group_1.style.setClasses(["layout-container"]);
			group_1.style.css({
				"box-shadow" : "outset 0 4px 8px 0px auto"
			});
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 0;
			group_1.setLayout(verticalLayout_1);
			(function(container){
				var group_2 = new cpr.controls.Container("header");
				group_2.style.css({
					"background-color" : "#FBF3EB"
				});
				var formLayout_1 = new cpr.controls.layouts.FormLayout();
				formLayout_1.scrollable = false;
				formLayout_1.horizontalSpacing = "0px";
				formLayout_1.verticalSpacing = "0px";
				formLayout_1.topMargin = "0px";
				formLayout_1.rightMargin = "0px";
				formLayout_1.bottomMargin = "0px";
				formLayout_1.leftMargin = "0px";
				formLayout_1.setColumns(["40px", "1fr", "1fr", "48px", "10px", "48px", "40px"]);
				formLayout_1.setRows(["10px", "1fr", "10px"]);
				group_2.setLayout(formLayout_1);
				(function(container){
					var output_1 = new cpr.controls.Output();
					output_1.value = "내손안의 냉장고";
					output_1.style.css({
						"color" : "#856C66",
						"font-weight" : "bold",
						"font-size" : "20px",
						"font-family" : "Kim jung chul Myungjo Regular"
					});
					container.addChild(output_1, {
						"colIndex": 1,
						"rowIndex": 1,
						"colSpan": 1,
						"rowSpan": 1
					});
					var group_3 = new cpr.controls.Container("recipeRegistration");
					var formLayout_2 = new cpr.controls.layouts.FormLayout();
					formLayout_2.scrollable = false;
					formLayout_2.horizontalSpacing = "0px";
					formLayout_2.verticalSpacing = "0px";
					formLayout_2.topMargin = "0px";
					formLayout_2.rightMargin = "0px";
					formLayout_2.bottomMargin = "0px";
					formLayout_2.leftMargin = "0px";
					formLayout_2.setColumns(["1fr"]);
					formLayout_2.setRows(["35px", "5px", "1fr"]);
					group_3.setLayout(formLayout_2);
					(function(container){
						var image_1 = new cpr.controls.Image();
						image_1.src = "theme/images/recipe_registration.svg";
						container.addChild(image_1, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var output_2 = new cpr.controls.Output();
						output_2.value = "레시피 등록";
						output_2.style.setClasses(["page-nav"]);
						container.addChild(output_2, {
							"colIndex": 0,
							"rowIndex": 2
						});
					})(group_3);
					container.addChild(group_3, {
						"colIndex": 5,
						"rowIndex": 1,
						"colSpan": 1,
						"rowSpan": 1,
						"width": 100,
						"height": 9
					});
					var group_4 = new cpr.controls.Container("receiptPhoto");
					var formLayout_3 = new cpr.controls.layouts.FormLayout();
					formLayout_3.scrollable = false;
					formLayout_3.horizontalSpacing = "0px";
					formLayout_3.verticalSpacing = "0px";
					formLayout_3.topMargin = "0px";
					formLayout_3.rightMargin = "0px";
					formLayout_3.bottomMargin = "0px";
					formLayout_3.leftMargin = "0px";
					formLayout_3.setColumns(["1fr"]);
					formLayout_3.setRows(["35px", "5px", "1fr"]);
					group_4.setLayout(formLayout_3);
					(function(container){
						var image_2 = new cpr.controls.Image();
						image_2.src = "theme/images/receipt_photo.svg";
						container.addChild(image_2, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var output_3 = new cpr.controls.Output();
						output_3.value = "영수증 촬영";
						output_3.style.setClasses(["page-nav"]);
						container.addChild(output_3, {
							"colIndex": 0,
							"rowIndex": 2
						});
					})(group_4);
					container.addChild(group_4, {
						"colIndex": 3,
						"rowIndex": 1,
						"colSpan": 1,
						"rowSpan": 1
					});
				})(group_2);
				container.addChild(group_2, {
					"autoSize": "width",
					"width": "100%",
					"height": "73px"
				});
				var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea1");
				container.addChild(embeddedApp_1, {
					"autoSize": "none",
					"width": "100%",
					"height": "calc(100% - 143px)"
				});
				var group_5 = new cpr.controls.Container("footer");
				group_5.style.setClasses(["page-nav"]);
				group_5.style.css({
					"background-color" : "#FFFFFF"
				});
				var formLayout_4 = new cpr.controls.layouts.FormLayout();
				formLayout_4.scrollable = false;
				formLayout_4.horizontalSpacing = "0px";
				formLayout_4.verticalSpacing = "0px";
				formLayout_4.topMargin = "0px";
				formLayout_4.rightMargin = "0px";
				formLayout_4.bottomMargin = "0px";
				formLayout_4.leftMargin = "0px";
				formLayout_4.setColumns(["40px", "40px", "1fr", "40px", "1fr", "40px", "1fr", "40px", "40px"]);
				formLayout_4.setRows(["10px", "50px", "10px"]);
				group_5.setLayout(formLayout_4);
				(function(container){
					var group_6 = new cpr.controls.Container();
					var formLayout_5 = new cpr.controls.layouts.FormLayout();
					formLayout_5.scrollable = false;
					formLayout_5.horizontalSpacing = "0px";
					formLayout_5.verticalSpacing = "0px";
					formLayout_5.topMargin = "0px";
					formLayout_5.rightMargin = "0px";
					formLayout_5.bottomMargin = "0px";
					formLayout_5.leftMargin = "0px";
					formLayout_5.setColumns(["1fr"]);
					formLayout_5.setRows(["30px", "1fr"]);
					group_6.setLayout(formLayout_5);
					(function(container){
						var output_4 = new cpr.controls.Output();
						output_4.value = "홈";
						output_4.style.setClasses(["page-nav"]);
						container.addChild(output_4, {
							"colIndex": 0,
							"rowIndex": 1
						});
						var image_3 = new cpr.controls.Image();
						image_3.src = "theme/images/home.svg";
						container.addChild(image_3, {
							"colIndex": 0,
							"rowIndex": 0
						});
					})(group_6);
					container.addChild(group_6, {
						"colIndex": 1,
						"rowIndex": 1
					});
					var group_7 = new cpr.controls.Container();
					var formLayout_6 = new cpr.controls.layouts.FormLayout();
					formLayout_6.scrollable = false;
					formLayout_6.horizontalSpacing = "0px";
					formLayout_6.verticalSpacing = "0px";
					formLayout_6.topMargin = "0px";
					formLayout_6.rightMargin = "0px";
					formLayout_6.bottomMargin = "0px";
					formLayout_6.leftMargin = "0px";
					formLayout_6.setColumns(["1fr"]);
					formLayout_6.setRows(["30px", "1fr"]);
					group_7.setLayout(formLayout_6);
					(function(container){
						var output_5 = new cpr.controls.Output();
						output_5.value = "냉장고";
						output_5.style.setClasses(["page-nav"]);
						container.addChild(output_5, {
							"colIndex": 0,
							"rowIndex": 1
						});
						var image_4 = new cpr.controls.Image();
						image_4.src = "theme/images/refrigerator.svg";
						container.addChild(image_4, {
							"colIndex": 0,
							"rowIndex": 0
						});
					})(group_7);
					container.addChild(group_7, {
						"colIndex": 3,
						"rowIndex": 1
					});
					var group_8 = new cpr.controls.Container();
					var formLayout_7 = new cpr.controls.layouts.FormLayout();
					formLayout_7.scrollable = false;
					formLayout_7.horizontalSpacing = "0px";
					formLayout_7.verticalSpacing = "0px";
					formLayout_7.topMargin = "0px";
					formLayout_7.rightMargin = "0px";
					formLayout_7.bottomMargin = "0px";
					formLayout_7.leftMargin = "0px";
					formLayout_7.setColumns(["1fr"]);
					formLayout_7.setRows(["30px", "1fr"]);
					group_8.setLayout(formLayout_7);
					(function(container){
						var output_6 = new cpr.controls.Output();
						output_6.value = "레시피";
						output_6.style.setClasses(["page-nav"]);
						container.addChild(output_6, {
							"colIndex": 0,
							"rowIndex": 1
						});
						var image_5 = new cpr.controls.Image();
						image_5.src = "theme/images/recipe.svg";
						container.addChild(image_5, {
							"colIndex": 0,
							"rowIndex": 0
						});
					})(group_8);
					container.addChild(group_8, {
						"colIndex": 5,
						"rowIndex": 1
					});
					var group_9 = new cpr.controls.Container();
					var formLayout_8 = new cpr.controls.layouts.FormLayout();
					formLayout_8.scrollable = false;
					formLayout_8.horizontalSpacing = "0px";
					formLayout_8.verticalSpacing = "0px";
					formLayout_8.topMargin = "0px";
					formLayout_8.rightMargin = "0px";
					formLayout_8.bottomMargin = "0px";
					formLayout_8.leftMargin = "0px";
					formLayout_8.setColumns(["1fr"]);
					formLayout_8.setRows(["30px", "1fr"]);
					group_9.setLayout(formLayout_8);
					(function(container){
						var output_7 = new cpr.controls.Output();
						output_7.value = "로그인";
						output_7.style.setClasses(["page-nav"]);
						container.addChild(output_7, {
							"colIndex": 0,
							"rowIndex": 1
						});
						var image_6 = new cpr.controls.Image();
						image_6.src = "theme/images/user.svg";
						container.addChild(image_6, {
							"colIndex": 0,
							"rowIndex": 0
						});
					})(group_9);
					container.addChild(group_9, {
						"colIndex": 7,
						"rowIndex": 1
					});
				})(group_5);
				container.addChild(group_5, {
					"autoSize": "width",
					"width": "600px",
					"height": "70px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "0px",
				"bottom": "0px",
				"width": "600px",
				"left": "calc(50% - 300px)"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "layout";
	cpr.core.Platform.INSTANCE.register(app);
})();
