/// start - data/embeddedRoutes
/*
 * Module URI: data/embeddedRoutes
 * SRC: data/embeddedRoutes.module.js
 *
 * This file was generated by eXBuilder6 compiler(1.0.5545), Don't edit manually.
 */
(function(){
	cpr.core.Module.define("data/embeddedRoutes", function(exports, globals, module){
		const embeddedRoutes = [
		  { path: "/recipe", loadApp: "app/recipe/recipe_main" }, // 정적 경로
		  { path: /^\/recipe\/(\d+)$/, loadApp: "app/recipe/recipe_detail" }, // id 값이 있는 경우
		  { path: "/recipe/search", loadApp: "app/recipe/recipe_search" }, // 쿼리 파라미터가 있는 경우
		  { path: "/users/login", loadApp: "app/login/login" },
		  { path: "/users/mypage", loadApp: "app/mypage/mypage"}
		];

		exports.embeddedRoutes = embeddedRoutes;
	});
})();
/// end - data/embeddedRoutes
/// start - module/recipe/createRecipeCard
/*
 * Module URI: module/recipe/createRecipeCard
 * SRC: module/recipe/createRecipeCard.module.js
 *
 * This file was generated by eXBuilder6 compiler(1.0.5545), Don't edit manually.
 */
(function(){
	cpr.core.Module.define("module/recipe/createRecipeCard", function(exports, globals, module){
		/************************************************
		 * createRecipeCard.module.js
		 * Created at 2025. 4. 22. 오전 11:30:01.
		 *
		 * @author gyrud
		 ************************************************/

		const createRecipeCard=(resultJson, recipeContainer)=> {
			for (let i = 0; i < resultJson.length; i++) {
				const recipeCard = new udc.recipe.recipe_card();
				recipeCard.title = resultJson[i].recipeName;
				recipeCard.difficulty = resultJson[i].difficulty;
				recipeCard.cookingTime = resultJson[i].cookingTime;
				recipeCard.author = resultJson[i].userNickname;
				recipeCard.likesCount = resultJson[i].likeCount;
				recipeCard.recipeImg = resultJson[i].fileUrl;
				recipeCard.authorImg = resultJson[i].userProfileImageUrl;
				recipeCard.calories = resultJson[i].calories+"kcal";
				
				const categories = resultJson[i].categories;
				for (let j = 0; j < categories.length; j++) {
				  const category = categories[j];
				  switch (category.recipeCategoryType) {
				    case "종류별":
				      recipeCard.typeCategory = "#" + category.recipeCategoryName;
				      break;
				    case "상황별":
				      recipeCard.situationCategory = "#" + category.recipeCategoryName;
				      break;
				    case "방법별":
				      recipeCard.methodCategory = "#" + category.recipeCategoryName;
				      break;
				    default:
				      break;
				  }
				}
				
				recipeContainer.addChild(recipeCard, {
				  width: "250px",
				  height: "400px",
				});	
			}
		}

		exports.createRecipeCard = createRecipeCard;
	});
})();
/// end - module/recipe/createRecipeCard
