/*
 * App URI: app/recipe/recipe_main
 * Source Location: app/recipe/recipe_main.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5481), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("app/recipe/recipe_main", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * contents_container.js
			 * Created at 2025. 4. 17. 오후 1:52:50.
			 *
			 * @author gyrud
			 ************************************************/

			const createRecipeCardModule = cpr.core.Module.require("module/recipe/createRecipeCard");
			const createRecipeCard = createRecipeCardModule.createRecipeCard;

			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad2(e){
				const popularRecipeListSms = app.lookup("popularRecipeListSms");
				popularRecipeListSms.send();
			}

			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출.
			 * 통신이 성공하면 발생합니다.
			 */
			function onPopularRecipeListSmsSubmitSuccess2(e){
				const popularRecipeListSms = e.control;
				
				const recipeContainer = app.lookup("popluarRecipeList"); 

				const result = popularRecipeListSms.xhr.responseText;
				const resultJson = JSON.parse(result);
				
				createRecipeCard(resultJson, recipeContainer);

				app.getContainer().redraw();
			};
			// End - User Script
			
			// Header
			var submission_1 = new cpr.protocols.Submission("popularRecipeListSms");
			submission_1.action = "/api/recipes/popular";
			if(typeof onPopularRecipeListSmsSubmitSuccess2 == "function") {
				submission_1.addEventListener("submit-success", onPopularRecipeListSmsSubmitSuccess2);
			}
			app.register(submission_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["contents-container"]);
			container.style.css({
				"background-color" : "#FFFFFF",
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var responsiveXYLayout_1 = new cpr.controls.layouts.ResponsiveXYLayout();
			responsiveXYLayout_1.scrollable = true;
			container.setLayout(responsiveXYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("popluarRecipeContainer");
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.scrollable = false;
			verticalLayout_1.spacing = 20;
			group_1.setLayout(verticalLayout_1);
			(function(container){
				var userDefinedControl_1 = new udc.recipe.recipe_title("popluarRecipeTitle");
				userDefinedControl_1.value = "인기 레시피";
				container.addChild(userDefinedControl_1, {
					"autoSize": "none",
					"width": "600px",
					"height": "30px"
				});
				var group_2 = new cpr.controls.Container("popluarRecipeList");
				var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
				flowLayout_1.scrollable = false;
				flowLayout_1.horizontalSpacing = 20;
				flowLayout_1.verticalSpacing = 20;
				flowLayout_1.horizontalAlign = "center";
				flowLayout_1.verticalAlign = "top";
				flowLayout_1.lineWrap = true;
				flowLayout_1.maxContentWidth = -1;
				group_2.setLayout(flowLayout_1);
				if(typeof onPopluarRecipeListBeforeDraw == "function") {
					group_2.addEventListener("before-draw", onPopluarRecipeListBeforeDraw);
				}
				container.addChild(group_2, {
					"autoSize": "height",
					"width": "600px",
					"height": ""
				});
			})(group_1);
			container.addChild(group_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "0px",
						"right": "0px",
						"left": "0px",
						"height": "1000px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "0px",
						"right": "0px",
						"left": "0px",
						"height": "1000px"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "0px",
						"right": "0px",
						"left": "0px",
						"height": "1000px"
					}
				]
			});
			if(typeof onBodyLoad2 == "function"){
				app.addEventListener("load", onBodyLoad2);
			}
		}
	});
	app.title = "recipe_main";
	cpr.core.Platform.INSTANCE.register(app);
})();
