/*
 * App URI: app/recipe/recipe_search
 * Source Location: app/recipe/recipe_search.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5481), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("app/recipe/recipe_search", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * contents_container.js
			 * Created at 2025. 4. 17. 오후 1:52:50.
			 *
			 * @author gyrud
			 ************************************************/;
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["contents-container"]);
			container.style.css({
				"background-color" : "#FFFFFF",
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var responsiveXYLayout_1 = new cpr.controls.layouts.ResponsiveXYLayout();
			container.setLayout(responsiveXYLayout_1);
			
			// UI Configuration
			var output_1 = new cpr.controls.Output();
			output_1.value = "recipe search";
			container.addChild(output_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "131px",
						"left": "161px",
						"width": "100px",
						"height": "20px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "131px",
						"left": "79px",
						"width": "49px",
						"height": "20px"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "131px",
						"left": "55px",
						"width": "34px",
						"height": "20px"
					}
				]
			});
		}
	});
	app.title = "recipe_search";
	cpr.core.Platform.INSTANCE.register(app);
})();
