/*
 * App URI: app/fridge/fridge_auto
 * Source Location: app/fridge/fridge_auto.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5545), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("app/fridge/fridge_auto", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * contents_container.js
			 * Created at 2025. 4. 17. 오후 1:52:50.
			 *
			 * @author gyrud
			 ************************************************/

			/*
			 * "Button" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
				var button = e.control;
				
				var fileInput = app.lookup("uploadImage");
				
				
			};
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["contents-container"]);
			container.style.css({
				"background-color" : "#FFFFFF",
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var responsiveXYLayout_1 = new cpr.controls.layouts.ResponsiveXYLayout();
			container.setLayout(responsiveXYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			group_1.setLayout(verticalLayout_1);
			(function(container){
				var group_2 = new cpr.controls.Container();
				var xYLayout_1 = new cpr.controls.layouts.XYLayout();
				group_2.setLayout(xYLayout_1);
				container.addChild(group_2, {
					"width": "400px",
					"height": "200px"
				});
				var group_3 = new cpr.controls.Container();
				var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
				group_3.setLayout(flowLayout_1);
				(function(container){
					var userDefinedControl_1 = new udc.image.UDCImageBox("uploadImage");
					container.addChild(userDefinedControl_1, {
						"width": "100px",
						"height": "100px"
					});
				})(group_3);
				container.addChild(group_3, {
					"width": "400px",
					"height": "147px"
				});
				var button_1 = new cpr.controls.Button();
				button_1.value = "Button";
				if(typeof onButtonClick == "function") {
					button_1.addEventListener("click", onButtonClick);
				}
				container.addChild(button_1, {
					"autoSize": "none",
					"width": "100px",
					"height": "20px"
				});
			})(group_1);
			container.addChild(group_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "0px",
						"left": "0px",
						"width": "600px",
						"height": "687px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023.984px)",
						"top": "0px",
						"left": "0px",
						"width": "293px",
						"height": "687px"
					}, 
					{
						"media": "all and (max-width: 499.984px)",
						"top": "0px",
						"left": "0px",
						"width": "205px",
						"height": "687px"
					}
				]
			});
		}
	});
	app.title = "fridge_auto";
	cpr.core.Platform.INSTANCE.register(app);
})();
